- name: Initial Setup
  include_tasks: initial_setup.yml
  when: skip_setup != true

- name: Install packages
  include_tasks: install_packages.yml

- name: Setup control plane
  include_tasks: setup_control_plane.yml
  when: control_plane | default(false) 
